# Generated by Django 5.2.2 on 2025-06-07 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_proveedor",
            new_name="is_staff",
        ),
    ]
