# Generated by Django 5.2.2 on 2025-06-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_auth_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telefono",
            field=models.CharField(
                help_text="Ej: +56912345678",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Telefono",
            ),
        ),
    ]
