# Generated by Django 5.2.2 on 2025-06-14 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_telefono"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="telefono",
        ),
    ]
