# Generated by Django 5.2.2 on 2025-11-04 23:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="El número debe tener el formato: '+56912345678'. Hasta 15 dígitos permitos.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
