# Generated by Django 5.2.2 on 2025-11-08 01:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rut',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="El rut debe tener el formato: '12.345.678-5' o '12345678-5'.", regex='^\\d{1,2}\\.?\\d{3}\\.?\\d{3}-[\\dkK]{1}$')]),
        ),
    ]
