# Generated by Django 5.2.2 on 2025-11-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alergias',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='codigo_pais',
            field=models.CharField(blank=True, default='+56', max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='contacto_emergencia_codigo',
            field=models.CharField(blank=True, default='+56', max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='contacto_emergencia_nombre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='contacto_emergencia_telefono',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='descripcion_comercio',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='direccion_calle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='direccion_comuna',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='direccion_numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notas_especiales',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rubro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
