# Generated by Django 5.2.2 on 2025-11-08 01:24

import django.db.models.deletion
import perfil_proveedor.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('descripcion_empresa', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_proveedor', to=settings.AUTH_USER_MODEL, validators=[perfil_proveedor.models.validar_proveedor])),
            ],
            options={
                'verbose_name': 'Perfil de Proveedor',
                'verbose_name_plural': 'Perfiles de Proveedores',
            },
        ),
    ]
