# Generated by Django 5.2.2 on 2025-06-24 04:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_servicio", models.CharField(max_length=100)),
                (
                    "tipo_servicio",
                    models.CharField(
                        choices=[
                            ("MED_GENERAL", "Medicina General"),
                            ("PEDIATRIA", "Pediatría"),
                            ("GINECOLOGIA", "Ginecología"),
                            ("DENTAL", "Odontología / Dental"),
                            ("PSICOLOGIA", "Psicología"),
                            ("KINESIOLOGIA", "Kinesiología"),
                            ("NUTRICION", "Nutrición"),
                            ("OFTALMOLOGIA", "Oftalmología"),
                            ("FISIOTERAPIA", "Fisioterapia"),
                            ("DERMATOLOGIA", "Dermatología"),
                            ("MASAJE", "Masoterapia"),
                            ("ESTETICA", "Estética Facial"),
                            ("PELUQUERIA", "Peluquería"),
                            ("DEPILACION", "Depilación Láser"),
                            ("MAQUILLAJE", "Maquillaje Profesional"),
                            ("UÑAS", "Manicure / Pedicure"),
                            ("SPA", "Spa y Relajación"),
                            ("ENTRENAMIENTO", "Entrenamiento Personal"),
                            ("YOGA", "Yoga"),
                            ("PILATES", "Pilates"),
                            ("ZUMBA", "Zumba"),
                            ("NATACION", "Clases de Natación"),
                            ("CROSSFIT", "CrossFit"),
                            ("TUTORIAS", "Tutorías Escolares"),
                            ("IDIOMAS", "Clases de Idiomas"),
                            ("MUSICA", "Clases de Música"),
                            ("ARTE", "Clases de Arte / Dibujo"),
                            ("DANZA", "Clases de Danza"),
                            ("APOYO_UNI", "Apoyo Universitario"),
                            ("ELECTRICIDAD", "Electricidad"),
                            ("GASFITERIA", "Gasfitería"),
                            ("PINTURA", "Pintura"),
                            ("LIMPIEZA", "Limpieza"),
                            ("REPARACIONES", "Reparaciones del Hogar"),
                            ("JARDINERIA", "Jardinería"),
                            ("MUDANZA", "Mudanza"),
                            ("INFORMATICA", "Soporte Informático"),
                            ("NIÑERA", "Niñera"),
                            ("CUIDADO_MAYORES", "Cuidado de Adultos Mayores"),
                            ("ANIMACION_INFANTIL", "Animación Infantil"),
                            ("FOTOGRAFIA", "Fotografía Familiar"),
                        ],
                        max_length=30,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                ("duracion", models.DurationField()),
                (
                    "precio",
                    models.IntegerField(
                        default=1000,
                        validators=[
                            django.core.validators.MinValueValidator(1000),
                            django.core.validators.MaxValueValidator(1000000),
                        ],
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        limit_choices_to={"is_staff": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("hora", models.TimeField()),
                ("comentario", models.TextField(blank=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        limit_choices_to={"is_staff": False},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="agenda.servicio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Disponibilidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("hora_inicio", models.TimeField()),
                ("cupos", models.PositiveIntegerField(default=1)),
                (
                    "proveedor",
                    models.ForeignKey(
                        limit_choices_to={"is_staff": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("proveedor", "fecha", "hora_inicio")},
            },
        ),
    ]
