# Generated by Django 5.2.2 on 2025-06-25 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cita",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("confirmada", "Confirmada"),
                    ("cancelada", "Cancelada"),
                    ("completada", "Completada"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
    ]
