# Generated by Django 5.2.2 on 2025-11-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_cita_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='tipo_servicio',
            field=models.CharField(choices=[('KINESIOLOGIA', 'Kinesiología'), ('NUTRICION', 'Nutrición'), ('FISIOTERAPIA', 'Fisioterapia'), ('DERMATOLOGIA', 'Dermatología'), ('MASAJE', 'Masoterapia'), ('ESTETICA', 'Estética Facial'), ('PELUQUERIA', 'Peluquería'), ('DEPILACION', 'Depilación Láser'), ('MAQUILLAJE', 'Maquillaje Profesional'), ('UÑAS', 'Manicure / Pedicure'), ('SPA', 'Spa y Relajación'), ('ENTRENAMIENTO', 'Entrenamiento Personal'), ('YOGA', 'Yoga'), ('PILATES', 'Pilates'), ('ZUMBA', 'Zumba'), ('NATACION', 'Clases de Natación'), ('CROSSFIT', 'CrossFit'), ('TUTORIAS', 'Tutorías Escolares'), ('IDIOMAS', 'Clases de Idiomas'), ('MUSICA', 'Clases de Música'), ('ARTE', 'Clases de Arte / Dibujo'), ('DANZA', 'Clases de Danza'), ('APOYO_UNI', 'Apoyo Universitario'), ('ELECTRICIDAD', 'Electricidad'), ('GASFITERIA', 'Gasfitería'), ('PINTURA', 'Pintura'), ('LIMPIEZA', 'Limpieza'), ('REPARACIONES', 'Reparaciones del Hogar'), ('JARDINERIA', 'Jardinería'), ('MUDANZA', 'Mudanza'), ('INFORMATICA', 'Soporte Informático'), ('FOTOGRAFIA', 'Fotografía Familiar')], max_length=30),
        ),
    ]
