# Generated by Django 5.2.2 on 2025-11-14 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_alter_servicio_tipo_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidad',
            name='servicio',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, to='agenda.servicio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipo_servicio',
            field=models.CharField(choices=[('ESTETICA', 'Estética y Cuidado Facial'), ('MASAJE', 'Masoterapia y Relajación'), ('PELUQUERIA', 'Peluquería'), ('BARBERIA', 'Barbería'), ('DEPILACION', 'Depilación'), ('UÑAS', 'Manicure / Pedicure'), ('MAQUILLAJE', 'Maquillaje Profesional'), ('SPA', 'Spa y Bienestar'), ('ENTRENAMIENTO', 'Entrenamiento Personal'), ('CLASES_DEPORTIVAS', 'Clases Deportivas Generales'), ('TUTORIAS', 'Tutorías Académicas'), ('APOYO_UNIVERSITARIO', 'Apoyo Universitario'), ('ELECTRICIDAD', 'Electricidad (Servicios Básicos)'), ('GASFITERIA', 'Gasfitería'), ('PINTURA', 'Pintura y Remodelación'), ('LIMPIEZA', 'Limpieza del Hogar'), ('REPARACIONES', 'Reparaciones Generales'), ('JARDINERIA', 'Jardinería y Paisajismo'), ('MUDANZA', 'Mudanzas y Transporte'), ('INFORMATICA', 'Soporte Informático'), ('FOTOGRAFIA', 'Fotografía'), ('OTROS', 'Otros Servicios')], max_length=30),
        ),
    ]
