# Generated by Django 5.2.2 on 2025-11-14 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_disponibilidad_servicio_alter_servicio_tipo_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disponibilidad',
            name='servicio',
        ),
    ]
